"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Download, FlaskConical, Sparkles } from "lucide-react";
import { useTheme } from "@/components/theme/ThemeProvider";
import { archonMonacoTheme, defineArchonMonacoThemes } from "@/components/theme/monacoThemes";

const MonacoDiff = dynamic(() => import("@monaco-editor/react").then((m) => m.DiffEditor), { ssr: false, loading: () => <div className="h-80 rounded-card border border-border-subtle bg-terminal p-4 text-sm text-text-low">Loading diff…</div> });

type Opt = { id: string; gasReportId: string; ruleId: string; title: string; category: string; file: string; lineStart: number | null; location: string; before: string; after: string; safety: "safe" | "review"; confidence: string | number; status: string; measurementLabel: string; estL2Delta: number | null; measuredL2Delta: number | null; estL1DeltaWei: string | null; measuredL1DeltaWei: string | null; annualSavingsUsd: string | number | null; patch: { oldText: string; newText: string } | null; gasDiff: { patchedSource?: string; gasReport?: string; label?: string } | null; notes: string | null; contractName: string; sourceHash: string | null; totals: unknown; assumptions: Record<string, unknown> | null };

function money(v: unknown) { return `$${Number(v ?? 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`; }
function download(filename: string, text: string) { const blob = new Blob([text], { type: "text/plain" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url); }

export function GasOptimizationDetail({ optimization: initial }: { optimization: Opt }) {
  const { theme } = useTheme();
  const [opt, setOpt] = useState(initial);
  const [notice, setNotice] = useState<string | null>(null);

  async function refresh() {
    const res = await fetch(`/api/gas/reports/${opt.gasReportId}/opt/${opt.id}`, { cache: "no-store" });
    if (!res.ok) return;
    const data = await res.json(); setOpt(data.optimization);
  }

  async function applyPatch() {
    setNotice(null);
    const res = await fetch(`/api/gas/reports/${opt.gasReportId}/apply`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ optId: opt.id }) });
    const data = await res.json();
    if (res.status === 202) { setNotice("Patch generation queued in the worker. Refresh when it completes."); return; }
    if (!res.ok) { setNotice(data.error ?? "Patch failed."); return; }
    await refresh(); setNotice("Patch ready with cached Foundry gas output.");
  }

  function generateGasTest() {
    const code = `// SPDX-License-Identifier: MIT\npragma solidity ^0.8.24;\n\n// Generated by Archon for ${opt.title}\n// Location: ${opt.location}\n// L2 delta: ${opt.measuredL2Delta ?? opt.estL2Delta ?? "n/a"}\n// L1/DA delta wei: ${opt.measuredL1DeltaWei ?? opt.estL1DeltaWei ?? "n/a"}\ncontract ArchonGas_${opt.ruleId.replace(/[^A-Za-z0-9_]/g, "_")} {\n    function test_documentedGasOptimization() public pure {}\n}\n`;
    download(`archon-gas-test-${opt.ruleId}.t.sol`, code);
  }

  return <div className="space-y-6">
    <header className="rounded-card border border-border-subtle bg-surface-1 p-5"><Link href={`/app/gas/${opt.gasReportId}`} className="inline-flex items-center gap-2 text-sm text-green-400"><ArrowLeft size={15}/> Back to gas report</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-pill border border-border-subtle bg-surface-2 px-3 py-1 text-xs text-text-mid">{opt.category}</span><span className={opt.safety === "safe" ? "rounded-pill border border-success/30 bg-success/10 px-3 py-1 text-xs text-success" : "rounded-pill border border-warning/30 bg-warning/10 px-3 py-1 text-xs text-warning"}>{opt.safety}</span><span className="rounded-pill border border-green-400/30 bg-green-400/10 px-3 py-1 text-xs text-green-400">{opt.measurementLabel}</span></div><h1 className="mt-3 text-3xl font-bold tracking-tight text-text-hi">{opt.title}</h1><p className="mt-2 font-mono text-sm text-text-low">{opt.contractName} · {opt.location}</p></div><div className="flex flex-wrap gap-2"><button onClick={applyPatch} className="inline-flex items-center gap-2 rounded-control bg-green-500 px-3 py-2 text-sm font-semibold text-on-green hover:bg-green-400"><Sparkles size={15}/> Apply patch</button><button onClick={generateGasTest} className="inline-flex items-center gap-2 rounded-control border border-border-subtle bg-surface-2 px-3 py-2 text-sm text-text-mid hover:text-green-400"><FlaskConical size={15}/> Generate gas test</button>{opt.gasDiff?.patchedSource ? <button onClick={() => download(`archon-${opt.ruleId}.sol`, opt.gasDiff!.patchedSource!)} className="inline-flex items-center gap-2 rounded-control border border-border-subtle bg-surface-2 px-3 py-2 text-sm text-text-mid hover:text-green-400"><Download size={15}/> Download patch</button> : null}</div></div>{notice ? <p className="mt-4 rounded-control border border-info/25 bg-info/10 px-3 py-2 text-sm text-info">{notice}</p> : null}</header>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_420px]">
      <main className="space-y-4"><section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Before / After</h2><div className="mt-4 overflow-hidden rounded-card border border-border-subtle"><MonacoDiff height="520px" original={opt.before} modified={opt.after} language="sol" theme={archonMonacoTheme(theme)} beforeMount={defineArchonMonacoThemes} options={{ readOnly: true, renderSideBySide: true, minimap: { enabled: false }, fontSize: 13, automaticLayout: true }} /></div></section>{opt.gasDiff?.gasReport ? <section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Foundry gas-diff proof</h2><pre className="mt-4 max-h-[520px] overflow-auto rounded-card bg-terminal p-4 text-xs leading-6 text-text-code">{opt.gasDiff.gasReport}</pre></section> : null}</main>
      <aside className="space-y-4"><Card title="Measured numbers"><Metric label="L2 gas delta" value={String(opt.measuredL2Delta ?? opt.estL2Delta ?? "—")} /><Metric label="L1/DA delta wei" value={String(opt.measuredL1DeltaWei ?? opt.estL1DeltaWei ?? "—")} /><Metric label="Annual savings" value={money(opt.annualSavingsUsd)} /></Card><Card title="Why it matters on Mantle"><p>Execution gas and calldata/DA fees are separate cost surfaces on Mantle. This optimization is ranked by its L2 delta, L1/DA delta, safety, and annual traffic assumption.</p></Card><Card title="Confidence"><p className="font-mono text-3xl text-green-400">{Math.round(Number(opt.confidence ?? 0) * 100)}%</p></Card><Card title="Notes"><p>{opt.notes ?? "No additional notes."}</p></Card><Card title="Source"><p className="break-all font-mono text-xs">{opt.sourceHash ?? "unavailable"}</p></Card></aside>
    </div>
  </div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-card border border-border-subtle bg-surface-1 p-4"><p className="mb-3 text-xs uppercase tracking-[0.12em] text-green-400">{title}</p><div className="space-y-3 text-sm leading-6 text-text-mid">{children}</div></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-control border border-border-subtle bg-terminal p-3"><p className="text-xs uppercase tracking-[0.12em] text-text-low">{label}</p><p className="mt-1 break-all font-mono text-sm text-text-hi">{value}</p></div>; }
