import Link from "next/link";
import { Bell, Search } from "lucide-react";
import { ArchonLogo, MainnetBadge, WalletChip } from "@/components/archon";
const nav = [
  ["Overview", "/app"], ["Audit Studio", "/app/audit/new"], ["Contract Context", "/app/context"], ["Reports", "/app/reports/demo"], ["Findings", "/app/reports/demo/findings/demo"], ["Generated Tests", "/app/reports/demo/tests"], ["Cost Guard", "/app/cost-guard"], ["On-chain Proof", "/app/proofs"], ["Settings", "/app#settings"],
] as const;
export default function AppLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <div className="min-h-screen bg-canvas text-text-hi"><aside className="fixed inset-y-0 left-0 w-[264px] border-r border-border-subtle bg-surface-1 p-5"><ArchonLogo/><nav className="mt-10 space-y-1">{nav.map(([label,href])=><Link key={label} href={href} className="block rounded-control px-3 py-2 text-sm text-text-mid hover:bg-surface-2 hover:text-green-400">{label}</Link>)}</nav></aside><div className="pl-[264px]"><header className="sticky top-0 z-10 flex h-16 items-center gap-4 border-b border-border-subtle bg-canvas/90 px-7 backdrop-blur"><button className="rounded-control border border-border-subtle bg-surface-2 px-3 py-2 text-sm text-text-mid">Founder workspace</button><label className="flex flex-1 items-center gap-2 rounded-control border border-border-subtle bg-surface-2 px-3 py-2 text-sm text-text-low"><Search size={16}/><input className="w-full border-0 bg-transparent p-0 text-text-hi placeholder:text-text-low focus:ring-0" placeholder="Search audits, contracts, findings..." /></label><MainnetBadge/><button className="rounded-control border border-border-subtle bg-surface-2 p-2 text-text-mid" aria-label="Notifications"><Bell size={18}/></button><WalletChip/></header><main className="p-7">{children}</main></div></div>;
}
