import Link from "next/link";
import { Activity, ArrowRight, FileText, ShieldCheck, Zap } from "lucide-react";
import { db } from "@/lib/db/client";
import { EmptyReportsState } from "@/components/archon";

type ReportRow = { id: string; contractName: string; riskScore: number; createdAt: string; proofTx: string | null };
type ScanRow = { id: string; status: string; progress: number; currentStage: string; createdAt: string };

export const dynamic = "force-dynamic";

export default async function AppOverview() {
  const [reportsResult, scansResult, countsResult] = await Promise.all([
    db.query<ReportRow>(`select r.id, r.contract_name as "contractName", r.risk_score as "riskScore", r.created_at as "createdAt", p.tx_hash as "proofTx" from reports r left join proofs p on p.report_id=r.id order by r.created_at desc limit 5`),
    db.query<ScanRow>(`select id,status,progress,current_stage as "currentStage",created_at as "createdAt" from scans order by created_at desc limit 5`),
    db.query<{ reports: string; critical: string; proofs: string }>(`select (select count(*) from reports)::text as reports, (select count(*) from findings where severity='critical')::text as critical, (select count(*) from proofs where tx_hash is not null)::text as proofs`),
  ]);
  const reports = reportsResult.rows;
  const scans = scansResult.rows;
  const counts = countsResult.rows[0] ?? { reports: "0", critical: "0", proofs: "0" };
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.14em] text-green-400">Workspace Overview</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-text-hi">Archon command center</h1><p className="mt-2 text-text-mid">Live audit activity, proof status, and next actions for Mantle Mainnet reports.</p></div><span className="rounded-pill border border-success/30 bg-success/10 px-3 py-1 text-sm text-success">Mantle Mainnet · Live</span></header>
    <section className="grid gap-4 md:grid-cols-4"><Kpi title="Audits This Week" value={counts.reports} note="live reports"/><Kpi title="Critical Findings Prevented" value={counts.critical} note="live findings"/><Kpi title="Estimated Gas Saved" value="$86" note="sample cost guard" sample/><Kpi title="Proofs Logged On-chain" value={counts.proofs} note="live proofs"/></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
      <main className="space-y-6"><section className="rounded-card border border-border-subtle bg-surface-1 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold text-text-hi">Recent Reports</h2><input placeholder="Filter reports…" className="rounded-control border-border-subtle bg-terminal text-sm text-text-hi placeholder:text-text-low"/></div>{reports.length ? <div className="overflow-hidden rounded-card border border-border-subtle"><table className="w-full text-left text-sm"><thead className="bg-surface-2 text-text-low"><tr><th className="p-3">Contract</th><th className="p-3">Risk</th><th className="p-3">Proof</th><th className="p-3">Action</th></tr></thead><tbody>{reports.map((r) => <tr key={r.id} className="border-t border-border-subtle"><td className="p-3 text-text-hi">{r.contractName}</td><td className="p-3 text-warning">{r.riskScore}</td><td className="p-3 text-text-mid">{r.proofTx ? "Logged" : "Pending"}</td><td className="p-3"><Link className="text-green-400" href={`/app/reports/${r.id}`}>Open</Link></td></tr>)}</tbody></table></div> : <EmptyReportsState/>}</section>
      <section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Active Scans</h2><div className="mt-4 space-y-3">{scans.length ? scans.map((scan) => <Link key={scan.id} href={`/app/scans/${scan.id}`} className="block rounded-control border border-border-subtle bg-terminal p-3"><div className="flex justify-between text-sm"><span className="font-mono text-text-hi">{scan.id.slice(0, 8)}…</span><span className="text-text-mid">{scan.status} · {scan.currentStage}</span></div><div className="mt-2 h-2 rounded-full bg-surface-3"><div className="h-full rounded-full bg-green-400" style={{ width: `${scan.progress}%` }}/></div></Link>) : <p className="rounded-control bg-terminal p-4 text-sm text-text-low">No active scans. Start a read-only audit when ready.</p>}</div></section></main>
      <aside className="space-y-6"><section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Quick Actions</h2><div className="mt-4 grid gap-2"><Action href="/app/audit/new" label="New Audit"/><Action href={reports[0] ? `/app/reports/${reports[0].id}` : "/app/audit/new"} label="Review Findings"/><Action href={reports[0] ? `/app/reports/${reports[0].id}/tests` : "/app/audit/new"} label="Generate Tests"/><Action href="/app/cost-guard" label="Run Cost Guard"/></div></section><section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Recent Activity</h2><div className="mt-4 space-y-3">{reports.slice(0,3).map((r) => <div key={r.id} className="flex gap-3 text-sm"><Activity className="mt-0.5 text-green-400" size={16}/><p className="text-text-mid">Report completed for <span className="text-text-hi">{r.contractName}</span>.</p></div>)}{!reports.length ? <p className="text-sm text-text-low">Activity appears after the first scan.</p> : null}</div></section><section className="rounded-card border border-success/30 bg-success/10 p-5"><h2 className="flex items-center gap-2 text-xl font-semibold text-text-hi"><ShieldCheck/> Workspace Health</h2><div className="mt-4 space-y-2 text-sm text-text-mid"><p>Overall risk posture: review required, not a guarantee.</p><p>Contracts monitored: {counts.reports}</p><p>Active alerts: 0 live / sample cost alerts in Cost Guard</p><p>Last scan: {scans[0]?.createdAt ? new Date(scans[0].createdAt).toLocaleString() : "none"}</p></div></section></aside>
    </div>
  </div>;
}
function Kpi({ title, value, note, sample }: { title: string; value: string; note: string; sample?: boolean }) { return <section className="rounded-card border border-border-subtle bg-surface-1 p-4"><p className="text-xs uppercase tracking-[0.12em] text-text-low">{title}</p><p className="mt-2 text-3xl font-bold text-text-hi">{value}</p><p className="mt-1 text-xs text-green-400">{note} {sample ? <span className="text-warning">· sample</span> : null}</p></section>; }
function Action({ href, label }: { href: string; label: string }) { return <Link href={href} className="flex items-center justify-between rounded-control border border-border-subtle bg-terminal px-3 py-2 text-sm text-text-mid hover:border-green-400/40 hover:text-green-400"><span>{label}</span><ArrowRight size={14}/></Link>; }
