"use client";

import { useMemo, useState } from "react";
import { Area, AreaChart, ResponsiveContainer } from "recharts";
import { AlertTriangle, RefreshCw, ShieldAlert } from "lucide-react";
import { CountUp, Reveal } from "@/components/motion";
import { CostTrendBars } from "@/components/cost-guard/CostTrendBars";
import { GasHotspotsDonut } from "@/components/cost-guard/GasHotspotsDonut";

const tabs = ["Overview", "Gas", "Infrastructure", "RPC", "AI Usage", "Alerts", "Settings"] as const;
const trend = [
  { day: "Mon", gas: 12, infra: 8, ai: 3 }, { day: "Tue", gas: 16, infra: 8, ai: 4 }, { day: "Wed", gas: 10, infra: 9, ai: 3 }, { day: "Thu", gas: 22, infra: 9, ai: 5 }, { day: "Fri", gas: 14, infra: 8, ai: 4 }, { day: "Sat", gas: 7, infra: 8, ai: 2 }, { day: "Sun", gas: 9, infra: 8, ai: 2 },
];
const hotspot = [{ name: "Proof logs", value: 34 }, { name: "Context fetch", value: 22 }, { name: "Scan queue", value: 28 }, { name: "Test generation", value: 16 }];
const spark = [{ v: 14 }, { v: 18 }, { v: 13 }, { v: 20 }, { v: 17 }, { v: 15 }, { v: 12 }];

export function CostGuardClient() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  const [auto, setAuto] = useState(false);
  const total = useMemo(() => trend.reduce((sum, row) => sum + row.gas + row.infra + row.ai, 0), []);
  // Sample dollar total for the donut centre, tied to the gas portion of the trend.
  const gasTotal = useMemo(() => Math.round(trend.reduce((sum, row) => sum + row.gas, 0) * 4.2), []);
  return <div className="space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.14em] text-green-400">Cost Guard</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-text-hi">Mantle cost intelligence</h1><p className="mt-2 max-w-3xl text-text-mid">Advisory gas, RPC, infrastructure, and AI-spend controls for demo-safe operations. Charts use curated realistic sample data until deeper telemetry is wired.</p></div><span className="rounded-pill border border-warning/30 bg-warning/10 px-3 py-1 text-xs uppercase tracking-[0.12em] text-warning">Sample data</span></header>
    <section className="flex flex-wrap items-center gap-3 rounded-card border border-border-subtle bg-surface-1 p-4"><select className="rounded-control border-border-subtle bg-terminal text-sm text-text-hi"><option>Mantle Mainnet</option></select><select className="rounded-control border-border-subtle bg-terminal text-sm text-text-hi"><option>Last 7 days</option><option>Last 30 days</option></select><button onClick={() => window.location.reload()} className="inline-flex items-center gap-2 rounded-control border border-border-subtle bg-surface-2 px-3 py-2 text-sm text-text-mid"><RefreshCw size={14}/> Refresh</button></section>
    <nav className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={tab === item ? "rounded-pill border border-green-400/35 bg-green-400/10 px-3 py-1.5 text-sm text-green-400" : "rounded-pill border border-border-subtle bg-surface-2 px-3 py-1.5 text-sm text-text-mid"}>{item}</button>)}</nav>
    {tab !== "Overview" ? <ComingSoon tab={tab}/> : <>
      <Reveal><div className="grid gap-4 md:grid-cols-4"><Kpi title="Estimated Monthly Spend" value={`$${Math.round(total * 4.2)}`} delta="sample projection"/><Kpi title="Gas Saved Potential" value="$86" delta="batch + cache"/><Kpi title="RPC Usage" value="42k" delta="reads / week"/><Kpi title="AI Token Spend" value="$3.40" delta="cached gpt-4o-mini"/></div></Reveal>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
        <main className="space-y-6">
          <section className="rounded-card border border-border-subtle bg-surface-1 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold text-text-hi">Cost Trend</h2><span className="text-xs uppercase tracking-[0.12em] text-warning">Sample</span></div><CostTrendBars data={trend}/></section>
          <section className="grid gap-6 lg:grid-cols-2"><div className="rounded-card border border-border-subtle bg-surface-1 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-text-hi">Gas Hotspots</h2><span className="text-xs uppercase tracking-[0.12em] text-warning">Sample</span></div><div className="mt-4"><GasHotspotsDonut data={hotspot} total={gasTotal}/></div></div><Recommendations/></section>
          <Runaway auto={auto} setAuto={setAuto}/>
        </main>
        <aside className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Top Cost Drivers</h2><div className="mt-4 space-y-3">{["Proof logging gas", "Repeated context fetches", "AI enrichment misses", "Build/restart loops", "Unbounded scan queue"].map((item, i) => <div key={item} className="rounded-control border border-border-subtle bg-terminal p-3"><div className="flex justify-between text-sm"><span className="text-text-hi">{item}</span><span className="text-green-400">{[34, 24, 18, 14, 10][i]}%</span></div><div className="mt-2 h-1.5 rounded-full bg-surface-3"><div className="h-full rounded-full bg-green-400" style={{ width: `${[34, 24, 18, 14, 10][i]}%` }}/></div></div>)}</div></aside>
      </div>
    </>}
  </div>;
}

function Kpi({ title, value, delta }: { title: string; value: string; delta: string }) { return <section className="archon-card-lift rounded-card border border-border-subtle bg-surface-1 p-4"><p className="text-xs uppercase tracking-[0.12em] text-text-low">{title}</p><p className="mt-2 text-2xl font-bold text-text-hi"><CountUp value={value}/></p><p className="text-xs text-green-400">{delta}</p><div className="mt-3 h-10"><ResponsiveContainer width="100%" height="100%"><AreaChart data={spark} margin={{ top: 2, bottom: 2, left: 0, right: 0 }}><defs><linearGradient id="spark-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--brand-500)" stopOpacity={0.35}/><stop offset="100%" stopColor="var(--brand-500)" stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="v" stroke="var(--brand-500)" strokeWidth={2} fill="url(#spark-fill)" isAnimationActive animationDuration={900} animationEasing="ease-out"/></AreaChart></ResponsiveContainer></div></section>; }
function Recommendations() { const rows = [["Reduce polling frequency", "High", "$28/mo"], ["Add cache layer", "High", "$24/mo"], ["Batch RPC calls", "Medium", "$18/mo"], ["Prevent redundant deployments", "High", "$42/mo"], ["Add idempotency keys", "Medium", "$12/mo"]]; return <section className="rounded-card border border-border-subtle bg-surface-1 p-5"><h2 className="text-xl font-semibold text-text-hi">Recommendations</h2><div className="mt-4 space-y-2">{rows.map(([name, impact, saving]) => <div key={name} className="flex items-center justify-between gap-3 rounded-control bg-terminal p-3 text-sm"><span className="text-text-hi">{name}</span><span className="rounded-pill border border-warning/30 bg-warning/10 px-2 py-1 text-xs text-warning">{impact}</span><span className="text-green-400">{saving}</span></div>)}</div></section>; }
function Runaway({ auto, setAuto }: { auto: boolean; setAuto: (value: boolean) => void }) { const alerts = ["High Cron Frequency", "Build Trigger Loops", "Excessive RPC Calls", "Missing Queue"]; return <section className="rounded-card border border-warning/30 bg-warning/5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-semibold text-text-hi"><ShieldAlert className="text-warning"/> Runaway Cost Guard</h2><p className="mt-1 text-sm text-text-mid">Advisory only. Archon never touches your cloud account.</p></div><label className="flex items-center gap-2 text-sm text-text-mid"><span>Auto-remediate</span><input type="checkbox" checked={auto} onChange={(event) => setAuto(event.target.checked)} className="rounded border-border-subtle bg-terminal text-green-400 focus:ring-green-400"/><span className="rounded-pill border border-border-subtle px-2 py-1 text-xs text-text-low">OFF by default</span></label></div><div className="mt-4 grid gap-3 md:grid-cols-4">{alerts.map((alert) => <div key={alert} className="rounded-card border border-border-subtle bg-terminal p-3"><AlertTriangle className="text-warning" size={18}/><p className="mt-2 text-sm font-semibold text-text-hi">{alert}</p><p className="mt-1 text-xs text-text-low">Advisory alert · no automatic action.</p></div>)}</div></section>; }
function ComingSoon({ tab }: { tab: string }) { return <section className="rounded-card border border-border-subtle bg-surface-1 p-10 text-center"><p className="text-xs uppercase tracking-[0.14em] text-warning">Coming soon</p><h2 className="mt-2 text-2xl font-semibold text-text-hi">{tab} detail view</h2><p className="mt-2 text-text-mid">This tab is intentionally visible for roadmap clarity, but it has no live controls yet.</p></section>; }
