import Link from "next/link";

const previews = [
  ["Audit Studio", "Paste Solidity or inspect a Mantle address read-only.", "7-stage scan"],
  ["Contract Context", "Verified source, ABI preview, protocol matches.", "RPC read-only"],
  ["Cost Guard", "Gas, RPC, infrastructure, and AI spend signals.", "Sample-labeled"],
  ["On-chain Proof", "IPFS metadata + ERC-8004 Reputation entry.", "Verifiable"],
] as const;

export default function MarketingHome() {
  return <main className="bg-canvas text-text-hi">
    <section className="mx-auto grid max-w-7xl gap-8 px-6 py-14 lg:grid-cols-[1fr_420px] lg:items-center"><div><p className="font-mono text-xs uppercase tracking-[0.16em] text-green-400">ERC-8004 trustless auditor · Mantle Mainnet</p><h1 className="mt-3 font-display text-5xl leading-[1.05] tracking-[-0.04em] text-text-hi md:text-7xl">AI-Powered Safety Layer for Mantle Mainnet</h1><p className="mt-4 max-w-xl text-lg leading-relaxed text-text-mid">Archon is an ERC-8004 trustless audit agent: it scans smart contracts, explains Mantle-specific risk, generates tests, and anchors reviewed reports as verifiable on-chain reputation.</p><div className="mt-5 flex flex-wrap gap-2">{["Mantle Mainnet Native", "ERC-8004 Trustless", "AI Risk Detection", "On-chain Proof"].map((chip) => <span key={chip} className="rounded-pill border border-green-400/30 bg-green-400/10 px-3 py-1 text-xs text-green-400">{chip}</span>)}</div><div className="mt-6 flex flex-wrap gap-3"><Link className="rounded-control bg-green-400 px-4 py-2.5 text-sm font-semibold text-on-green transition-colors hover:bg-green-300" href="/app/audit/new">Start Mainnet Audit</Link><Link className="rounded-control border border-border-subtle px-4 py-2.5 text-sm text-text-mid transition-colors hover:border-border-emphasis hover:text-text-hi" href="/app/proofs">View Proofs</Link></div></div><HeroVisual/></section>
    <section id="product" className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-3 md:grid-cols-4">{previews.map(([title, body, tag]) => <article key={title} className="rounded-card border border-border-subtle bg-surface-1 p-4 transition-colors hover:border-border-emphasis"><p className="font-mono text-xs uppercase tracking-[0.12em] text-green-400">{tag}</p><h2 className="mt-2 text-base font-semibold text-text-hi">{title}</h2><p className="mt-1.5 text-sm leading-relaxed text-text-mid">{body}</p><div className="mt-3 rounded-control bg-terminal p-2.5 font-mono text-xs text-text-code">{title === "On-chain Proof" ? "report_hash == rederived_hash" : title === "Cost Guard" ? "gas + rpc + ai · sample" : title === "Contract Context" ? "verifiedSource: true" : "Code Parse → Proof Logger"}</div></article>)}</div></section>
    <section className="mx-auto max-w-7xl px-6 py-10"><h2 className="text-2xl font-bold tracking-tight text-text-hi">From Code to On-chain Confidence in 3 Steps</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{[["1", "Scan Contract", "Read-only source or address intake on Mantle."], ["2", "Analyze Risk", "Static analysis, Mantle rules, AI explanation, tests."], ["3", "Log Proof On-chain", "IPFS metadata and ERC-8004 Reputation entry after explicit approval."]].map(([n,t,b]) => <div key={n} className="rounded-card border border-border-subtle bg-surface-1 p-4"><span className="grid size-7 place-items-center rounded-full bg-green-400 font-mono text-sm text-on-green">{n}</span><h3 className="mt-3 text-base font-semibold text-text-hi">{t}</h3><p className="mt-1.5 text-sm leading-relaxed text-text-mid">{b}</p></div>)}</div></section>
    <footer id="docs" className="mx-auto grid max-w-7xl gap-6 border-t border-border-subtle px-6 py-8 text-sm text-text-mid md:grid-cols-4"><Footer title="Product" items={["Audit Studio", "Context Explorer", "Cost Guard", "Proofs"]}/><Footer title="Resources" items={["Architecture", "Demo script", "ADR log", "API health"]}/><Footer title="Company" items={["Mantle-native", "Hackathon build", "Read-only scans", "Careful findings"]}/><Footer title="Connect" items={["GitHub", "Mantle Explorer", "ERC-8004", "Archon Agent"]}/></footer>
  </main>;
}
function HeroVisual() { return <div className="relative rounded-card border border-border-subtle bg-surface-1 p-5"><div className="absolute right-4 top-4 rounded-pill border border-success/30 bg-success/10 px-2.5 py-1 text-xs text-success">Built for Mantle Mainnet · Live</div><div className="mt-10 grid place-items-center rounded-card border border-green-400/20 bg-terminal p-8"><div className="relative h-52 w-52 rounded-full border border-green-400/40"><div className="absolute inset-8 rounded-card border border-border-subtle"/><div className="absolute left-1/2 top-3 h-44 w-px bg-green-400/40"/><div className="absolute left-8 right-8 top-1/2 h-px bg-green-400/40"/><p className="absolute inset-x-0 top-[42%] text-center font-display text-5xl text-green-400">Α</p></div></div></div>; }
function Footer({ title, items }: { title: string; items: string[] }) { return <div><h3 className="text-sm font-semibold text-text-hi">{title}</h3><ul className="mt-3 space-y-2 text-text-mid">{items.map((item) => <li key={item} className="transition-colors hover:text-text-hi">{item}</li>)}</ul></div>; }
