import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { copyFile, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { db } from "@/lib/db/client";
import type { GasOptimizationRuleResult } from "@/lib/gas/rules";

const execFileAsync = promisify(execFile);
const MEASUREMENT_TIMEOUT_MS = Number(process.env.ARCHON_GAS_MEASUREMENT_TIMEOUT_MS ?? 90_000);
const FORGE_BIN = process.env.FORGE_BIN ?? "forge";

export type GasPatchMeasurement = {
  ruleId: string;
  status: "measured" | "estimated" | "skipped";
  safety: "safe" | "review";
  before: string;
  after: string;
  l2GasDelta: number | null;
  l1DaDeltaWei: string | null;
  note: string;
};

export type GasMeasurementProfile = {
  version: "archon.gasMeasurement.v1";
  rulesetHash: string;
  contractHash: string;
  status: "measured" | "degraded" | "skipped";
  measuredAt: string;
  source: "foundry" | "deterministic-estimate";
  patches: GasPatchMeasurement[];
  forge: {
    attempted: boolean;
    ok: boolean;
    command: string | null;
    gasReport: string | null;
    error: string | null;
  };
};

type MeasureInput = {
  source: string;
  sourceFile: string;
  contractName: string;
  opportunities: GasOptimizationRuleResult[];
  onProgress?: (message: string) => Promise<void>;
};

function hash(value: string) {
  return createHash("sha256").update(value).digest("hex");
}

function rulesetHash(opportunities: GasOptimizationRuleResult[]) {
  return hash(JSON.stringify(opportunities.map((item) => ({ id: item.id, safety: item.safety, before: item.before, after: item.after, patch: item.patch }))));
}

function cacheKey(contractHash: string, rulesHash: string) {
  return `gas-measurement:v1:${contractHash}:${rulesHash}`;
}

async function readCache(key: string) {
  const result = await db.query<{ response: GasMeasurementProfile }>("select response from ai_cache where cache_key = $1", [key]);
  return result.rows[0]?.response ?? null;
}

async function writeCache(key: string, profile: GasMeasurementProfile) {
  await db.query(
    `insert into ai_cache (cache_key, prompt_version, response, created_at)
     values ($1, 'archon.gasMeasurement.v1', $2::jsonb, now())
     on conflict (cache_key) do update set response = excluded.response, created_at = excluded.created_at`,
    [key, JSON.stringify(profile)],
  );
}

function applySafePatches(source: string, safeRules: GasOptimizationRuleResult[]) {
  let patched = source;
  const applied: GasOptimizationRuleResult[] = [];
  for (const rule of safeRules) {
    const oldText = rule.patch.oldText;
    const occurrences = patched.split(oldText).length - 1;
    if (occurrences !== 1) continue;
    patched = patched.replace(oldText, rule.patch.newText);
    applied.push(rule);
  }
  return { patched, applied };
}

function buildHarness(contractName: string) {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {${contractName}} from "../src/${contractName}.sol";

/// @notice Synthetic compile/smoke harness generated by Archon for read-only gas measurement.
contract ${contractName}ArchonGasMeasurementTest is Test {
    ${contractName} internal target;

    function setUp() public {
        target = new ${contractName}();
    }

    function test_archon_measurement_harness_smoke() public view {
        assertTrue(address(target) != address(0));
    }
}
`;
}

async function runForgeProject(source: string, sourceFile: string, contractName: string) {
  const project = await mkdtemp(path.join(tmpdir(), "archon-gas-measure-"));
  const srcDir = path.join(project, "src");
  const testDir = path.join(project, "test");
  await mkdir(srcDir, { recursive: true });
  await mkdir(testDir, { recursive: true });
  await writeFile(path.join(project, "foundry.toml"), "[profile.default]\nsrc = 'src'\ntest = 'test'\nout = 'out'\nlibs = ['lib']\noptimizer = true\noptimizer_runs = 200\n");
  await writeFile(path.join(srcDir, `${contractName}.sol`), source);
  await writeFile(path.join(testDir, `${contractName}.t.sol`), buildHarness(contractName));

  // Preserve the original source alongside the generated project for debugging, without mutating it.
  await copyFile(sourceFile, path.join(project, "Original.sol")).catch(() => undefined);

  const args = ["test", "--gas-report", "--root", project];
  const { stdout, stderr } = await execFileAsync(FORGE_BIN, args, {
    timeout: MEASUREMENT_TIMEOUT_MS,
    maxBuffer: 8 * 1024 * 1024,
    env: process.env,
  });
  return { command: `${FORGE_BIN} ${args.join(" ")}`, gasReport: `${stdout}\n${stderr}`.trim() };
}

function estimatedPatch(rule: GasOptimizationRuleResult): GasPatchMeasurement {
  return {
    ruleId: rule.id,
    status: rule.safety === "safe" ? "estimated" : "skipped",
    safety: rule.safety,
    before: rule.before,
    after: rule.after,
    l2GasDelta: rule.estL2Delta,
    l1DaDeltaWei: null,
    note: rule.safety === "safe"
      ? "Foundry measurement unavailable; deterministic rule estimate retained and clearly labeled."
      : "Review-only patch is not auto-applied for measurement.",
  };
}

export async function measureGasOptimizations(input: MeasureInput): Promise<GasMeasurementProfile> {
  const contractHash = hash(input.source);
  const ruleHash = rulesetHash(input.opportunities);
  const key = cacheKey(contractHash, ruleHash);
  const cached = await readCache(key);
  if (cached) {
    await input.onProgress?.("Gas measurement cache hit for this contract/ruleset.");
    return cached;
  }

  const safeRules = input.opportunities.filter((item) => item.safety === "safe");
  const base: GasMeasurementProfile = {
    version: "archon.gasMeasurement.v1",
    rulesetHash: ruleHash,
    contractHash,
    status: safeRules.length ? "degraded" : "skipped",
    measuredAt: new Date().toISOString(),
    source: "deterministic-estimate",
    patches: input.opportunities.map(estimatedPatch),
    forge: { attempted: false, ok: false, command: null, gasReport: null, error: null },
  };

  if (!safeRules.length) {
    base.forge.error = "No safety=safe gas patches available for automatic measurement.";
    await writeCache(key, base);
    return base;
  }

  await input.onProgress?.(`Preparing Foundry measurement for ${safeRules.length} safe patch${safeRules.length === 1 ? "" : "es"}.`);
  const { patched, applied } = applySafePatches(input.source, safeRules);
  if (!applied.length || patched === input.source) {
    base.forge.error = "Safe patch oldText did not match exactly once; measurement degraded to estimates.";
    await writeCache(key, base);
    return base;
  }

  try {
    await input.onProgress?.("Running Foundry gas report for patched harness.");
    const report = await runForgeProject(patched, input.sourceFile, input.contractName);
    const profile: GasMeasurementProfile = {
      ...base,
      status: "measured",
      source: "foundry",
      forge: { attempted: true, ok: true, command: report.command, gasReport: report.gasReport, error: null },
      patches: input.opportunities.map((rule) => ({
        ...estimatedPatch(rule),
        status: applied.some((appliedRule) => appliedRule.id === rule.id && appliedRule.where === rule.where) ? "measured" : estimatedPatch(rule).status,
        note: applied.some((appliedRule) => appliedRule.id === rule.id && appliedRule.where === rule.where)
          ? "Safe exact patch was applied in the generated Foundry harness; see gas report for executable evidence. Per-function attribution lands in the next measurement refinement."
          : estimatedPatch(rule).note,
      })),
    };
    await writeCache(key, profile);
    return profile;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    base.forge = { attempted: true, ok: false, command: `${FORGE_BIN} test --gas-report`, gasReport: null, error: message.slice(0, 2000) };
    await input.onProgress?.(`Foundry measurement degraded: ${base.forge.error}`);
    await writeCache(key, base);
    return base;
  }
}

export async function loadFixtureMeasurement() {
  const fixture = path.join(process.cwd(), "lib/gas/__fixtures__/GasRulesFixture.sol");
  return readFile(fixture, "utf8");
}
